# Generated by Django 4.2.4 on 2023-08-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "validity",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 months"),
                            (2, "2 months"),
                            (3, "3 months"),
                            (4, "4 months"),
                            (5, "5 months"),
                            (6, "6 months"),
                            (7, "7 months"),
                            (8, "8 months"),
                            (9, "9 months"),
                            (10, "10 months"),
                            (11, "11 months"),
                            (12, "12 months"),
                        ]
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                ("server_ip", models.GenericIPAddressField(protocol="IPv4")),
                ("nms_key", models.CharField(max_length=50)),
                ("mac_address", models.CharField(max_length=17)),
            ],
        ),
    ]
