# Generated by Django 4.2.4 on 2023-08-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_b", "0005_rename_validity_license_validity_months"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="validity_months",
            field=models.PositiveIntegerField(),
        ),
    ]
