# Generated by Django 4.2.4 on 2023-08-04 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_b", "0007_alter_license_validity_months"),
    ]

    operations = [
        migrations.RenameField(
            model_name="license",
            old_name="nms_key",
            new_name="nmssecuritykey",
        ),
    ]
